//! Embedded runtime component manifest — generated by `build.rs` from the
//! `LIONOS_COMPONENTS` env export (the `lionos setup` component picker), merged
//! with the compulsory kernel core. `ENABLED` is the set of components to
//! register/print at boot; `REQUIRED` is the always-present core; `CSV` is the
//! joined list for the boot marker.
//!
//! Components are always compiled in (hybrid gating — see the design spec); this
//! manifest controls which ones are *active/registered* at boot, not which are
//! linked. So dropping a component in the picker disables it here, it does not
//! shrink the kernel binary.

include!(concat!(env!("OUT_DIR"), "/component_manifest.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_always_contains_the_required_core() {
        // The required kernel core must be present no matter what the picker said.
        for r in REQUIRED {
            assert!(ENABLED.contains(r), "required component {} missing from ENABLED", r);
        }
    }

    #[test]
    fn manifest_required_and_enabled_are_deduped_stable() {
        // No duplicates; REQUIRED appears first, then any user extras.
        for (i, r) in REQUIRED.iter().enumerate() {
            assert_eq!(&ENABLED[i], r, "required core must lead ENABLED");
        }
        let mut seen = std::collections::HashSet::new();
        for k in ENABLED {
            assert!(seen.insert(k), "duplicate component in ENABLED: {k}");
        }
    }

    #[test]
    fn csv_matches_enabled_order() {
        assert_eq!(CSV, ENABLED.join(","));
    }
}