#![no_std]
#![no_main]

//! LionOS kernel boot entry point — bootloader 0.11.17.
//!
//! The bootloader enters long mode, sets up initial paging, reads the BIOS/UEFI
//! memory map, and hands a `&'static mut BootInfo` to `_start` (generated by
//! `bootloader_api::entry_point!`). We re-validate the memory map (defense in
//! depth — see `memory.rs`), consume the framebuffer descriptor (the 0.11
//! handoff), and print summaries over serial before parking the CPU. The
//! Week-1 placeholder marker `LIONOS_INIT_OK` is preserved (CI greps for it);
//! `LIONOS_HANDOFF_OK` appears only once the handoff is consumed and validated.

extern crate alloc;

use core::fmt::Write;
use core::panic::PanicInfo;

use bootloader_api::entry_point;
use bootloader_api::info::MemoryRegionKind;
use bootloader_api::BootInfo;

use alloc::boxed::Box;
use alloc::vec::Vec;

use lionos_kernel::ffi;
use lionos_kernel::frames;
use lionos_kernel::framebuffer::{self, FramebufferInfo};
use lionos_kernel::heap;
use lionos_kernel::interrupts;
use lionos_kernel::memory::{self, Region, RegionKind};
use lionos_kernel::paging;
use lionos_kernel::serial;

extern "C" {
    /// End of the kernel image (linker.ld `_end`) — the frame allocator's floor.
    static _end: u8;
}

/// Boot marker printed to COM1 on success. CI greps for this exact string.
///
/// Overridable at build time via the `LIONOS_BOOT_MARKER` env var so CI can
/// run a real negative test (boot with a wrong marker -> assert it is absent).
fn boot_marker() -> &'static str {
    option_env!("LIONOS_BOOT_MARKER").unwrap_or("LIONOS_INIT_OK")
}

/// Map a bootloader 0.11 `MemoryRegionKind` onto our validator's coarser
/// `RegionKind`. 0.11 collapses every non-usable E820/UEFI type into
/// `UnknownUefi/UnknownBios`, so reserved vs non-usable is no longer
/// distinguishable — both map to `Reserved` (the validator only enforces
/// usable/usable disjointness). The enum is non-exhaustive, so unknown future
/// variants are treated as reserved.
fn to_kind(k: MemoryRegionKind) -> RegionKind {
    match k {
        MemoryRegionKind::Usable => RegionKind::Usable,
        MemoryRegionKind::Bootloader
        | MemoryRegionKind::UnknownUefi(_)
        | MemoryRegionKind::UnknownBios(_) => RegionKind::Reserved,
        _ => RegionKind::Reserved,
    }
}

fn kernel_main(boot_info: &'static mut BootInfo) -> ! {
    serial::init();

    // core::fmt re-verification. The Week-1 stub triple-faulted when it called
    // `writeln!` under the 0.9.35 bootloader; with bootloader 0.11 this should
    // now work (CI greps the deterministic LIONOS_FMT_OK line).
    let mut s = serial::serial();
    writeln!(s, "LIONOS_FMT_OK count={}", 42).unwrap();

    // memory_regions are BYTE addresses (start/end exclusive) now — no frames.
    let mut raw = [(0u64, 0u64, RegionKind::Usable); memory::MAX_REGIONS];
    let mut n = 0;
    for region in boot_info.memory_regions.iter() {
        raw[n] = (region.start, region.end, to_kind(region.kind));
        n += 1;
    }

    let mut regions = [Region::empty(); memory::MAX_REGIONS];
    match memory::validate_regions_bytes(&raw[..n], &mut regions) {
        Ok(count) => {
            let usable = regions[..count]
                .iter()
                .filter(|r| r.kind == RegionKind::Usable)
                .count();
            serial::write_str("LIONOS_MEM_MAP regions=");
            serial::write_dec(count as u64);
            serial::write_str(" usable=");
            serial::write_dec(usable as u64);
            serial::write_str("\r\n");

            // Print the first few usable regions so CI/`xxd`-style debugging
            // can eyeball the addresses without needing `core::fmt`.
            for r in regions[..count].iter().filter(|r| r.kind == RegionKind::Usable).take(4) {
                serial::write_str("  usable 0x");
                serial::write_hex(r.start);
                serial::write_str(" len=");
                serial::write_dec(r.len);
                serial::write_str("\r\n");
            }

            // --- Month 2: physical frame allocator (pure accounting) ---
            // Floor = end of the kernel image (incl. bss) rounded up, plus a
            // safety margin for bootloader 0.11's page tables/bootinfo. The
            // allocator never dereferences frames, so no paging is needed yet.
            let kernel_end = unsafe { (&_end as *const u8 as usize) as u64 };
            let floor = (kernel_end + 4095) & !4095;
            let floor = floor + 0x40000;
            let mut usable = [(0u64, 0u64); memory::MAX_REGIONS];
            let mut uc = 0;
            for r in regions[..count].iter().filter(|r| r.kind == RegionKind::Usable) {
                usable[uc] = (r.start, r.end());
                uc += 1;
            }
            // SAFETY: single-CPU boot, one init call, after the map validates.
            unsafe {
                if frames::init_frames(&usable[..uc], floor).is_err() {
                    serial::write_str("LIONOS_FRAMES_INIT_ERROR\r\n");
                }
            }
            serial::write_str("LIONOS_FRAMES total=");
            serial::write_dec(frames::total_frames());
            serial::write_str(" free=");
            serial::write_dec(frames::free_frames());
            serial::write_str(" used=");
            serial::write_dec(frames::used_frames());
            serial::write_str("\r\n");
            // Exercise alloc/dealloc so a regression fails loudly at boot.
            if let Some(f) = frames::allocate_frame() {
                serial::write_str("LIONOS_FRAME_ALLOC phys=");
                serial::write_hex(f * 4096); // frame number -> physical address
                serial::write_str("\r\n");
                frames::deallocate_frame(f);
            }

            serial::write_raw(b"LIONOS_HANDOFF_OK\r\n");
        }
        Err(e) => {
            serial::write_raw(b"LIONOS_MEM_MAP_ERROR code=");
            serial::write_dec(e.code());
            serial::write_str("\r\n");
        }
    }

    // --- Framebuffer handoff (bootloader 0.11) ---
    // `framebuffer` is an FFI-safe `Optional<FrameBuffer>`. `buffer().as_ptr()`
    // is the mapped VIRTUAL base (page-aligned; the physical address is not
    // exposed by the API). `validate` only checks page alignment + overflow, so
    // --- Framebuffer handoff (bootloader 0.11) ---
    // `framebuffer` is an FFI-safe `Optional<FrameBuffer>`. `buffer().as_ptr()`
    // is the mapped VIRTUAL base (page-aligned; the physical address is not
    // exposed by the API). `validate` only checks page alignment + overflow, so
    // the page-aligned virtual base is the correct input.
    match boot_info.framebuffer.as_mut() {
        Some(fb) => {
            let info = fb.info();
            let fb_desc = FramebufferInfo {
                address: fb.buffer().as_ptr() as u64,
                width: info.width as u32,
                height: info.height as u32,
                bpp: (info.bytes_per_pixel as u32 * 8) as u8,
                // bootloader_api's `stride` is in PIXELS; our validator's
                // `pitch` is in bytes per scanline. Saturating is safe: the
                // validator's total-size check still catches real overflows.
                pitch: (info.stride as u32).saturating_mul(info.bytes_per_pixel as u32),
            };
            match framebuffer::validate(&fb_desc) {
                Ok(v) => {
                    serial::write_raw(b"LIONOS_FB_OK");
                    serial::write_str(" w=");
                    serial::write_dec(v.width as u64);
                    serial::write_str(" h=");
                    serial::write_dec(v.height as u64);
                    serial::write_str(" bpp=");
                    serial::write_dec(v.bpp as u64);
                    serial::write_str(" pitch=");
                    serial::write_dec(v.pitch as u64);
                    serial::write_str("\r\n");

                    // --- Deep C integration: draw a test pattern via the C
                    // framebuffer library (kernel/c/fb.c). The descriptor was
                    // validated, so pitch/width/height/bpp guarantees hold and
                    // the C code additionally bounds-checks every pixel. ---
                    let base = fb.buffer_mut().as_mut_ptr();
                    // SAFETY: `base` is the mapped, validated framebuffer; all
                    // dimensions come from the just-validated descriptor.
                    unsafe {
                        ffi::fb_clear(base, v.width, v.height, v.pitch, v.bpp as u32, 0x000000);
                        ffi::fb_fill_rect(
                            base, v.width, v.height, v.pitch, v.bpp as u32,
                            10, 10, 60, 40, 0x0000ff,
                        );
                        ffi::fb_hline(
                            base, v.width, v.height, v.pitch, v.bpp as u32,
                            120, 0, v.width / 2, 0x00ff00,
                        );
                        ffi::fb_pixel(
                            base, v.width, v.height, v.pitch, v.bpp as u32,
                            5, 5, 0xffffff,
                        );
                    }
                    serial::write_raw(b"LIONOS_FB_DRAW_OK\r\n");
                }
                Err(e) => {
                    serial::write_raw(b"LIONOS_FB_ERROR code=");
                    serial::write_dec(e.code());
                    serial::write_str("\r\n");
                }
            }
        }
        None => {
            serial::write_raw(b"LIONOS_FB_NONE\r\n");
        }
    }

    // --- Mixed-language (C + assembly) support check (unchanged from 0.9) ---
    // Exercise the FFI bridge so a silent regression in the C/asm objects fails
    // loudly at boot instead of surfacing weeks later. Every printed value is
    // deterministic for a given VM, so CI can assert on it cheaply. This is the
    // first real consumer of the C (`c/support.c`) and assembly (`asm/cpu.s`)
    // objects linked in by `build.rs`.
    serial::write_str("\r\n[ffi] cr3=");
    serial::write_hex(ffi::read_cr3());
    serial::write_str(" cpuid=");
    serial::write_hex(ffi::cpuid(1, 0)[0] as u64);

    // C `lion_memset`: all eight bytes -> 0xAB.
    let mut buf = [0u8; 8];
    // SAFETY: `buf` is 8 writable bytes with the call's lifetime.
    unsafe { ffi::memset(buf.as_mut_ptr(), 0xAB, buf.len()) };
    serial::write_str(" memset=");
    serial::write_hex(u64::from_le_bytes(buf)); // expect 0xabababababababab

    // C `lion_memcpy` + `lion_memcmp` round-trip.
    let src = b"LION-FFI";
    let mut buf2 = [0u8; 8];
    // SAFETY: `buf2` is 8 writable bytes, `src` 8 readable bytes, disjoint.
    unsafe { ffi::memcpy(buf2.as_mut_ptr(), src.as_ptr(), src.len()) };
    serial::write_str(" memcpy_ok=");
    // SAFETY: both sides are 8 readable bytes for the call.
    let memcpy_ok: bool =
        unsafe { ffi::memcmp(buf2.as_ptr(), src.as_ptr(), src.len()) } == 0;
    serial::write_dec(memcpy_ok as u64);

    serial::write_str(" vendor=");
    for b in ffi::cpuid_vendor() {
        serial::write_byte(b);
    }
    serial::write_str("\r\n");

    // --- Deep mixed-language: C calling assembly, plus more assembly ops ---
    // `cpu_leaf1_edx` is a C function (support.c) that internally calls the asm
    // `lion_cpuid` — the full Rust -> C -> asm chain in one call.
    serial::write_str("LIONOS_CPUID_LEAF1EDX=");
    serial::write_hex(ffi::cpu_leaf1_edx() as u64);
    serial::write_str("\r\n");

    // Direct Rust -> asm: RFLAGS snapshot (deterministic: IF=0 at boot -> 0x2),
    // EFER MSR read (safe in long mode), and an atomic spinlock round-trip via
    // asm `xchg8`.
    serial::write_str("LIONOS_ASM rflags=");
    serial::write_hex(ffi::read_rflags());
    serial::write_str(" efer=");
    serial::write_hex(ffi::read_msr(0xC000_0080)); // IA32_EFER
    serial::write_str(" spin=");
    let mut lock = 0u8;
    // SAFETY: `&mut lock` is a valid writable byte for each call.
    let prev = unsafe { ffi::xchg8(&mut lock, 1) };       // 0 -> acquired
    let reacquired = unsafe { ffi::xchg8(&mut lock, 1) }; // 1 -> already held
    let released = unsafe { ffi::xchg8(&mut lock, 0) };   // release; was held -> 1
    serial::write_dec(((prev == 0) && (reacquired == 1) && (released == 1)) as u64);
    serial::write_str("\r\n");

    // Week-1 CI checkpoint preserved regardless of the handoff result.
    serial::write_raw(boot_marker().as_bytes());
    serial::write_raw(b"\r\n");

    // --- Month 2: interrupt bring-up (GDT → IDT → PIC → PIT → sti) ---
    // (Page-table takeover is deferred: bootloader 0.11's virtual↔physical
    // mapping isn't derivable, so CR3 for a fresh PML4 can't be computed. See
    // paging.rs.)
    interrupts::init();
    serial::write_str("LIONOS_IRQ_FLAGS=");
    serial::write_hex(ffi::read_rflags()); // expect IF=1 → bit 9 set (…202)
    serial::write_str("\r\n");

    // Wait for the PIT timer to fire a few times (bounded: headless CI can
    // still drain if the timer is somehow absent).
    let mut spins = 0u64;
    while interrupts::ticks() < 25 && spins < 2_000_000_000 {
        ffi::pause();
        spins += 1;
    }
    serial::write_str("LIONOS_TIMER_TICKS=");
    serial::write_dec(interrupts::ticks());
    serial::write_str("\r\n");

    serial::write_str("LIONOS_KBD_ARMED count=");
    serial::write_dec(interrupts::key_count());
    serial::write_str("\r\n");

    // --- Month 2: kernel heap via `#[global_allocator]` ---
    // SAFETY: single-CPU boot, called exactly once before any allocation.
    unsafe { heap::init_heap(); }

    // Exercise the heap so a regression fails loudly at boot: a growing `Vec`
    // (needs alloc+realloc) and a `Box` (needs alloc on the heap, not the stack).
    let mut nums = Vec::new();
    for i in 0..64 {
        nums.push(i * 3);
    }
    let sum: u32 = nums.iter().sum();
    let boxed = Box::new(0xA5u8);

    serial::write_str("LIONOS_HEAP_OK cap=");
    serial::write_dec(heap::KERNEL_ALLOC.capacity() as u64);
    serial::write_str(" used=");
    serial::write_dec(heap::KERNEL_ALLOC.used() as u64);
    serial::write_str(" sum=");
    serial::write_dec(sum as u64);
    serial::write_str(" box=");
    serial::write_hex(u64::from(*boxed));
    serial::write_str("\r\n");

    // --- Month 2: page-table ownership marker ---
    // The bootloader 0.11 does NOT identity-map its own page tables (reading
    // CR3's physical address faults), so the kernel cannot read/write them to
    // extend the map in place. True paging = building + switching to the
    // kernel's OWN page tables (a dedicated follow-up; `paging.rs` has the pure
    // index/entry helpers + tests). Here we only report our CR3 (a safe,
    // register-only read).
    serial::write_str("LIONOS_PML4 cr3=");
    serial::write_hex(paging::current_cr3());
    serial::write_str("\r\n");

    // Drain any deferred work the ISRs queued, then park with interrupts on so
    // the timer keeps ticking (future months run a scheduler here).
    interrupts::run_deferred();
    serial::write_str("LIONOS_IRQ_OK\r\n");
    loop {
        interrupts::run_deferred();
        ffi::hlt();
    }
}

entry_point!(kernel_main);

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    serial::init();
    serial::write_raw(b"PANIC\r\n");
    ffi::hlt();
}
