#![no_std]
#![no_main]

//! LionOS kernel boot entry point — bootloader 0.11.17.
//!
//! The bootloader enters long mode, sets up initial paging, reads the BIOS/UEFI
//! memory map, and hands a `&'static mut BootInfo` to `_start` (generated by
//! `bootloader_api::entry_point!`). We re-validate the memory map (defense in
//! depth — see `memory.rs`), consume the framebuffer descriptor (the 0.11
//! handoff), and print summaries over serial before parking the CPU. The
//! Week-1 placeholder marker `LIONOS_INIT_OK` is preserved (CI greps for it);
//! `LIONOS_HANDOFF_OK` appears only once the handoff is consumed and validated.

extern crate alloc;

use core::fmt::Write;
use core::panic::PanicInfo;

use bootloader_api::config::Mapping;
use bootloader_api::entry_point;
use bootloader_api::info::MemoryRegionKind;
use bootloader_api::{BootInfo, BootloaderConfig};

use alloc::boxed::Box;
use alloc::vec::Vec;

use lionos_kernel::ffi;
use lionos_kernel::frames;
use lionos_kernel::framebuffer::{self, FramebufferInfo};
use lionos_kernel::heap;
use lionos_kernel::interrupts;
use lionos_kernel::memory::{self, Region, RegionKind};
use lionos_kernel::paging;
use lionos_kernel::sched;
use lionos_kernel::serial;

extern "C" {
    /// End of the kernel image (linker.ld `_end`) — the frame allocator's floor.
    static _end: u8;
}

// --- Month-3 scheduler self-test (module scope; `static`/`fn` can't be item
// bodies). Three tasks share this one busy-counting closure; each runs it on
// its own stack and the PIT preempts mid-count, so ROTATIONS grows across all
// three — the interleave proof behind the LIONOS_SCHED marker.
static mut ROTATIONS: u64 = 0;

fn task_closure() {
    // SAFETY: single-CPU boot; only tasks touch ROTATIONS, all single-threaded.
    let mut t = 0u64;
    for _ in 0..100_000 {
        t = t.wrapping_add(1);
        // Volatile store to the shared counter via a raw pointer (dodges the
        // static_mut_refs lint); each task folds into the same ROTATIONS.
        unsafe { core::ptr::write_volatile(core::ptr::addr_of_mut!(ROTATIONS), t) };
    }
}

/// Boot marker printed to COM1 on success. CI greps for this exact string.
///
/// Overridable at build time via the `LIONOS_BOOT_MARKER` env var so CI can
/// run a real negative test (boot with a wrong marker -> assert it is absent).
fn boot_marker() -> &'static str {
    option_env!("LIONOS_BOOT_MARKER").unwrap_or("LIONOS_INIT_OK")
}

/// Map a bootloader 0.11 `MemoryRegionKind` onto our validator's coarser
/// `RegionKind`. 0.11 collapses every non-usable E820/UEFI type into
/// `UnknownUefi/UnknownBios`, so reserved vs non-usable is no longer
/// distinguishable — both map to `Reserved` (the validator only enforces
/// usable/usable disjointness). The enum is non-exhaustive, so unknown future
/// variants are treated as reserved.
fn to_kind(k: MemoryRegionKind) -> RegionKind {
    match k {
        MemoryRegionKind::Usable => RegionKind::Usable,
        MemoryRegionKind::Bootloader
        | MemoryRegionKind::UnknownUefi(_)
        | MemoryRegionKind::UnknownBios(_) => RegionKind::Reserved,
        _ => RegionKind::Reserved,
    }
}

fn kernel_main(boot_info: &'static mut BootInfo) -> ! {
    serial::init();

    // core::fmt re-verification. The Week-1 stub triple-faulted when it called
    // `writeln!` under the 0.9.35 bootloader; with bootloader 0.11 this should
    // now work (CI greps the deterministic LIONOS_FMT_OK line).
    let mut s = serial::serial();
    writeln!(s, "LIONOS_FMT_OK count={}", 42).unwrap();

    // memory_regions are BYTE addresses (start/end exclusive) now — no frames.
    let mut raw = [(0u64, 0u64, RegionKind::Usable); memory::MAX_REGIONS];
    let mut n = 0;
    for region in boot_info.memory_regions.iter() {
        raw[n] = (region.start, region.end, to_kind(region.kind));
        n += 1;
    }

    let mut regions = [Region::empty(); memory::MAX_REGIONS];
    match memory::validate_regions_bytes(&raw[..n], &mut regions) {
        Ok(count) => {
            let usable = regions[..count]
                .iter()
                .filter(|r| r.kind == RegionKind::Usable)
                .count();
            serial::write_str("LIONOS_MEM_MAP regions=");
            serial::write_dec(count as u64);
            serial::write_str(" usable=");
            serial::write_dec(usable as u64);
            serial::write_str("\r\n");

            // Print the first few usable regions so CI/`xxd`-style debugging
            // can eyeball the addresses without needing `core::fmt`.
            for r in regions[..count].iter().filter(|r| r.kind == RegionKind::Usable).take(4) {
                serial::write_str("  usable 0x");
                serial::write_hex(r.start);
                serial::write_str(" len=");
                serial::write_dec(r.len);
                serial::write_str("\r\n");
            }

            // --- Month 2: physical frame allocator (pure accounting) ---
            // Floor = end of the kernel image (incl. bss) rounded up, plus a
            // safety margin for bootloader 0.11's page tables/bootinfo. The
            // allocator never dereferences frames, so no paging is needed yet.
            let kernel_end = unsafe { (&_end as *const u8 as usize) as u64 };
            let floor = (kernel_end + 4095) & !4095;
            let floor = floor + 0x40000;
            let mut usable = [(0u64, 0u64); memory::MAX_REGIONS];
            let mut uc = 0;
            for r in regions[..count].iter().filter(|r| r.kind == RegionKind::Usable) {
                usable[uc] = (r.start, r.end());
                uc += 1;
            }
            // SAFETY: single-CPU boot, one init call, after the map validates.
            unsafe {
                if frames::init_frames(&usable[..uc], floor).is_err() {
                    serial::write_str("LIONOS_FRAMES_INIT_ERROR\r\n");
                }
            }
            serial::write_str("LIONOS_FRAMES total=");
            serial::write_dec(frames::total_frames());
            serial::write_str(" free=");
            serial::write_dec(frames::free_frames());
            serial::write_str(" used=");
            serial::write_dec(frames::used_frames());
            serial::write_str("\r\n");
            // Exercise alloc/dealloc so a regression fails loudly at boot.
            if let Some(f) = frames::allocate_frame() {
                serial::write_str("LIONOS_FRAME_ALLOC phys=");
                serial::write_hex(f * 4096); // frame number -> physical address
                serial::write_str("\r\n");
                frames::deallocate_frame(f);
            }

            serial::write_raw(b"LIONOS_HANDOFF_OK\r\n");

            // --- M2W3c: page-table takeover ---
            // With `mappings.physical_memory` enabled, `BootInfo` exposes
            // `physical_memory_offset` — a virt window over ALL physical memory.
            // This unblocks owning the page tables: the kernel can now read/write
            // any physical frame (incl. the bootloader's own table frames), so it
            // can build its own PML4 and switch CR3 to a real physical root.
            // Runs while IF=0 (before interrupts::init below), so no interrupt
            // can fault through the window mid-switch.
            match boot_info.physical_memory_offset.into_option() {
                Some(offset) => match unsafe { paging::takeover(offset) } {
                    Ok(new_cr3) => {
                        serial::write_str("LIONOS_TAKEOVER cr3=");
                        serial::write_hex(new_cr3);
                        serial::write_str("\r\n");
                        // Confirm the switch really took (CR3 now our frame).
                        let cr3_now = paging::current_cr3() & paging::ADDR_MASK;
                        serial::write_str("LIONOS_CR3_NOW=");
                        serial::write_hex(cr3_now);
                        serial::write_str(" owned=");
                        serial::write_dec((cr3_now == new_cr3) as u64);
                        serial::write_str("\r\n");

                        // Map/unmap round-trip: allocate a data frame, map it at a
                        // free 512 GiB region (canonical), write+read through the
                        // virtual address, and translate it back to physical.
                        if let Some(idx) = unsafe { paging::find_free_top_index(offset) } {
                            // Make `virt` canonical: low half for idx<256, else
                            // sign-extend bits 48..63.
                            let mut virt = (idx as u64) << 39;
                            if idx >= 256 {
                                virt |= 0xFFFF_0000_0000_0000;
                            }
                            if let Some(dframe) = frames::allocate_frame() {
                                let dphys = dframe * 4096;
                                match unsafe { paging::map_page(offset, virt, dphys) } {
                                    Ok(()) => {
                                        // SAFETY: map_page just mapped `virt`
                                        // present+writable at `dphys`.
                                        unsafe { *(virt as *mut u64) = 0xDEAD_BEEF_CAFE_F00D };
                                        let back = unsafe { *(virt as *const u64) };
                                        let pte = unsafe { paging::translate(offset, virt) };
                                        serial::write_str("LIONOS_MAP_RW back=");
                                        serial::write_hex(back);
                                        serial::write_str(" pte=");
                                        serial::write_hex(pte);
                                        serial::write_str(" phys_ok=");
                                        serial::write_dec(((pte & paging::ADDR_MASK) == dphys) as u64);
                                        serial::write_str("\r\n");
                                    }
                                    Err(_) => serial::write_str("LIONOS_MAP_ERR\r\n"),
                                }
                            }
                        }
                    }
                    Err(_) => serial::write_str("LIONOS_TAKEOVER_ERR\r\n"),
                },
                None => serial::write_str("LIONOS_NO_PHYS_MAPPING\r\n"),
            }
        }
        Err(e) => {
            serial::write_raw(b"LIONOS_MEM_MAP_ERROR code=");
            serial::write_dec(e.code());
            serial::write_str("\r\n");
        }
    }

    // --- Framebuffer handoff (bootloader 0.11) ---
    // `framebuffer` is an FFI-safe `Optional<FrameBuffer>`. `buffer().as_ptr()`
    // is the mapped VIRTUAL base (page-aligned; the physical address is not
    // exposed by the API). `validate` only checks page alignment + overflow, so
    // --- Framebuffer handoff (bootloader 0.11) ---
    // `framebuffer` is an FFI-safe `Optional<FrameBuffer>`. `buffer().as_ptr()`
    // is the mapped VIRTUAL base (page-aligned; the physical address is not
    // exposed by the API). `validate` only checks page alignment + overflow, so
    // the page-aligned virtual base is the correct input.
    match boot_info.framebuffer.as_mut() {
        Some(fb) => {
            let info = fb.info();
            let fb_desc = FramebufferInfo {
                address: fb.buffer().as_ptr() as u64,
                width: info.width as u32,
                height: info.height as u32,
                bpp: (info.bytes_per_pixel as u32 * 8) as u8,
                // bootloader_api's `stride` is in PIXELS; our validator's
                // `pitch` is in bytes per scanline. Saturating is safe: the
                // validator's total-size check still catches real overflows.
                pitch: (info.stride as u32).saturating_mul(info.bytes_per_pixel as u32),
            };
            match framebuffer::validate(&fb_desc) {
                Ok(v) => {
                    serial::write_raw(b"LIONOS_FB_OK");
                    serial::write_str(" w=");
                    serial::write_dec(v.width as u64);
                    serial::write_str(" h=");
                    serial::write_dec(v.height as u64);
                    serial::write_str(" bpp=");
                    serial::write_dec(v.bpp as u64);
                    serial::write_str(" pitch=");
                    serial::write_dec(v.pitch as u64);
                    serial::write_str("\r\n");

                    // --- Deep C integration: draw a test pattern via the C
                    // framebuffer library (kernel/c/fb.c). The descriptor was
                    // validated, so pitch/width/height/bpp guarantees hold and
                    // the C code additionally bounds-checks every pixel. ---
                    let base = fb.buffer_mut().as_mut_ptr();
                    // SAFETY: `base` is the mapped, validated framebuffer; all
                    // dimensions come from the just-validated descriptor.
                    unsafe {
                        ffi::fb_clear(base, v.width, v.height, v.pitch, v.bpp as u32, 0x000000);
                        ffi::fb_fill_rect(
                            base, v.width, v.height, v.pitch, v.bpp as u32,
                            10, 10, 60, 40, 0x0000ff,
                        );
                        ffi::fb_hline(
                            base, v.width, v.height, v.pitch, v.bpp as u32,
                            120, 0, v.width / 2, 0x00ff00,
                        );
                        ffi::fb_pixel(
                            base, v.width, v.height, v.pitch, v.bpp as u32,
                            5, 5, 0xffffff,
                        );
                    }
                    serial::write_raw(b"LIONOS_FB_DRAW_OK\r\n");

                    // --- Month 3: framebuffer bitmap-text driver (W1D3) ---
                    // Render text into the same validated framebuffer so the
                    // glyph layer is exercised at boot; CI greps LIONOS_FB_TEXT.
                    let fb_desc = FramebufferInfo {
                        address: fb.buffer().as_ptr() as u64,
                        width: v.width,
                        height: v.height,
                        bpp: v.bpp,
                        pitch: v.pitch,
                    };
                    // SAFETY: `fb_desc` is the just-validated framebuffer.
                    unsafe {
                        lionos_kernel::drivers::fbtext::draw_str(
                            &fb_desc, 80, 120, "LIONOS v0.2.0", 0x00ff00,
                        );
                    }
                    serial::write_raw(b"LIONOS_FB_TEXT ok\r\n");
                }
                Err(e) => {
                    serial::write_raw(b"LIONOS_FB_ERROR code=");
                    serial::write_dec(e.code());
                    serial::write_str("\r\n");
                }
            }
        }
        None => {
            serial::write_raw(b"LIONOS_FB_NONE\r\n");
        }
    }

    // --- Mixed-language (C + assembly) support check (unchanged from 0.9) ---
    // Exercise the FFI bridge so a silent regression in the C/asm objects fails
    // loudly at boot instead of surfacing weeks later. Every printed value is
    // deterministic for a given VM, so CI can assert on it cheaply. This is the
    // first real consumer of the C (`c/support.c`) and assembly (`asm/cpu.s`)
    // objects linked in by `build.rs`.
    serial::write_str("\r\n[ffi] cr3=");
    serial::write_hex(ffi::read_cr3());
    serial::write_str(" cpuid=");
    serial::write_hex(ffi::cpuid(1, 0)[0] as u64);

    // C `lion_memset`: all eight bytes -> 0xAB.
    let mut buf = [0u8; 8];
    // SAFETY: `buf` is 8 writable bytes with the call's lifetime.
    unsafe { ffi::memset(buf.as_mut_ptr(), 0xAB, buf.len()) };
    serial::write_str(" memset=");
    serial::write_hex(u64::from_le_bytes(buf)); // expect 0xabababababababab

    // C `lion_memcpy` + `lion_memcmp` round-trip.
    let src = b"LION-FFI";
    let mut buf2 = [0u8; 8];
    // SAFETY: `buf2` is 8 writable bytes, `src` 8 readable bytes, disjoint.
    unsafe { ffi::memcpy(buf2.as_mut_ptr(), src.as_ptr(), src.len()) };
    serial::write_str(" memcpy_ok=");
    // SAFETY: both sides are 8 readable bytes for the call.
    let memcpy_ok: bool =
        unsafe { ffi::memcmp(buf2.as_ptr(), src.as_ptr(), src.len()) } == 0;
    serial::write_dec(memcpy_ok as u64);

    serial::write_str(" vendor=");
    for b in ffi::cpuid_vendor() {
        serial::write_byte(b);
    }
    serial::write_str("\r\n");

    // --- Deep mixed-language: C calling assembly, plus more assembly ops ---
    // `cpu_leaf1_edx` is a C function (support.c) that internally calls the asm
    // `lion_cpuid` — the full Rust -> C -> asm chain in one call.
    serial::write_str("LIONOS_CPUID_LEAF1EDX=");
    serial::write_hex(ffi::cpu_leaf1_edx() as u64);
    serial::write_str("\r\n");

    // Direct Rust -> asm: RFLAGS snapshot (deterministic: IF=0 at boot -> 0x2),
    // EFER MSR read (safe in long mode), and an atomic spinlock round-trip via
    // asm `xchg8`.
    serial::write_str("LIONOS_ASM rflags=");
    serial::write_hex(ffi::read_rflags());
    serial::write_str(" efer=");
    serial::write_hex(ffi::read_msr(0xC000_0080)); // IA32_EFER
    serial::write_str(" spin=");
    let mut lock = 0u8;
    // SAFETY: `&mut lock` is a valid writable byte for each call.
    let prev = unsafe { ffi::xchg8(&mut lock, 1) };       // 0 -> acquired
    let reacquired = unsafe { ffi::xchg8(&mut lock, 1) }; // 1 -> already held
    let released = unsafe { ffi::xchg8(&mut lock, 0) };   // release; was held -> 1
    serial::write_dec(((prev == 0) && (reacquired == 1) && (released == 1)) as u64);
    serial::write_str("\r\n");

    // --- Month-1 NASM + C string smoke test (master-plan language lay) ---
    // The plan's Day-1 lay is NASM for port-I/O + CPU utils and C for string
    // helpers. These calls exercise the NASM objects (asm/port_io.asm,
    // cpu_utils.asm) and the C string helpers (c/string_utils.c) so a silent
    // regression in either assembler/compiler's output fails loudly. All
    // printed values are deterministic for a given VM -> CI can grep them.
    serial::write_str("LIONOS_NASM");
    // port I/O: outw/inw round-trip is not guaranteed (some ports ignore
    // writes), so we only assert the calls don't fault -> they ran.
    // SAFETY: 0x80 (POST) is a conventional, always-valid write port.
    unsafe {
        ffi::nasm_outb(0x80, 0xAA);
        ffi::nasm_outw(0x80, 0x55AA);
        ffi::nasm_inb(0x80);
        ffi::nasm_inw(0x80);
    }
    ffi::nasm_io_wait();
    ffi::nasm_cpu_pause();
    // CPU utils: EFER MSR read is stable in long mode; CPUID vendor string is
    // deterministic per VM.
    serial::write_str(" efer_nasm=");
    serial::write_hex(ffi::nasm_read_msr(0xC000_0080));
    serial::write_str(" vendor_nasm=");
    let q = ffi::nasm_cpuid_query(0, 0);
    // vendor is in ebx, edx, ecx (same byte packing the GAS cpuid_vendor uses)
    let mut vendor = [0u8; 12];
    // SAFETY: `vendor[..12]` is a valid writable 12-byte buffer.
    unsafe {
        core::ptr::copy_nonoverlapping(q[1].to_ne_bytes().as_ptr(), vendor.as_mut_ptr().add(0), 4);
        core::ptr::copy_nonoverlapping(q[3].to_ne_bytes().as_ptr(), vendor.as_mut_ptr().add(4), 4);
        core::ptr::copy_nonoverlapping(q[2].to_ne_bytes().as_ptr(), vendor.as_mut_ptr().add(8), 4);
    }
    for &b in &vendor {
        serial::write_byte(b);
    }
    serial::write_str("\r\n");

    // C string helpers (c/string_utils.c): length + compare + hex-format are
    // fully deterministic. `b"LION\0"` guarantees the NUL terminator `strlen_c`
    // and `strcmp_c` stop at (an unterminated `b"LION"` would over-read).
    const S: &[u8] = b"LION\0";
    // SAFETY: S is a valid NUL-terminated readable string of length 4.
    let len = unsafe { ffi::strlen_c(S.as_ptr()) };
    serial::write_str("LIONOS_C_STR len=");
    serial::write_dec(len as u64);
    // Compare the string against itself -> must be 0.
    // SAFETY: both are valid NUL-terminated readable strings.
    let cmp = unsafe { ffi::strcmp_c(S.as_ptr(), S.as_ptr()) };
    serial::write_str(" cmp=");
    serial::write_dec(cmp as u64);
    // Drill the itoa_hex helper -> "0x00000000deadbeef" (19 bytes incl. NUL).
    let mut hexbuf = [0u8; 19];
    // SAFETY: hexbuf is 19 writable bytes.
    unsafe { ffi::itoa_hex(0xDEAD_BEEFu64, hexbuf.as_mut_ptr()) };
    serial::write_str(" hex=");
    // SAFETY: itoa_hex wrote a NUL-terminated string into the 19-byte buffer.
    let hexstr = unsafe { core::slice::from_raw_parts(hexbuf.as_ptr(), 18) };
    for &b in hexstr {
        serial::write_byte(b);
    }
    serial::write_str("\r\n");

    // C memmove (c/support.c): overlap handling. Copy mem[2..8] onto mem[0..6]
    // (forward, dst<src — the memmove-safe direction). If memmove were to
    // corrupt the overlap, the LIONOS_C_MEMMOVE marker still prints, so we also
    // print mem[0..4] as a deterministic value CI can grep.
    let mut mem = *b"LION-123456\0";
    // SAFETY: mem is a 12-byte writable buffer; src = mem+2, dst = mem, n=6
    // overlaps forward, which memmove handles correctly.
    unsafe { ffi::memmove(mem.as_mut_ptr(), mem.as_ptr().add(2), 6) };
    // dst[0..4] = mem[2..6] = "ON-1" → 0x312d4e4f ("-N…" packed little-endian).
    serial::write_str("LIONOS_C_MEMMOVE first4=");
    serial::write_hex(u64::from(u32::from_le_bytes([mem[0], mem[1], mem[2], mem[3]])));
    serial::write_str("\r\n");

    // C++17 + Zig language-lay smoke (Month 3). Deterministic magic constants
    // prove both new objects linked into liblionos_ffi.a and ran.
    serial::write_str("LIONOS_CPP magic=");
    serial::write_hex(ffi::cpp_magic() as u64);
    serial::write_str(" LIONOS_ZIG magic=");
    serial::write_hex(ffi::zig_magic() as u64);
    serial::write_str(" table=");
    serial::write_hex(ffi::zig_table_magic() as u64);
    serial::write_str("\r\n");

    // Week-1 CI checkpoint preserved regardless of the handoff result.
    serial::write_raw(boot_marker().as_bytes());
    serial::write_raw(b"\r\n");

    // --- Month 2: interrupt bring-up (GDT → IDT → PIC → PIT → sti) ---
    // (Page-table takeover is deferred: bootloader 0.11's virtual↔physical
    // mapping isn't derivable, so CR3 for a fresh PML4 can't be computed. See
    // paging.rs.)
    interrupts::init();
    serial::write_str("LIONOS_IRQ_FLAGS=");
    serial::write_hex(ffi::read_rflags()); // expect IF=1 → bit 9 set (…202)
    serial::write_str("\r\n");

    // Wait for the PIT timer to fire a few times (bounded: headless CI can
    // still drain if the timer is somehow absent).
    let mut spins = 0u64;
    while interrupts::ticks() < 25 && spins < 2_000_000_000 {
        ffi::pause();
        spins += 1;
    }
    serial::write_str("LIONOS_TIMER_TICKS=");
    serial::write_dec(interrupts::ticks());
    serial::write_str("\r\n");

    serial::write_str("LIONOS_KBD_ARMED count=");
    serial::write_dec(interrupts::key_count());
    serial::write_str("\r\n");

    // --- Month 2: kernel heap via `#[global_allocator]` ---
    // SAFETY: single-CPU boot, called exactly once before any allocation.
    unsafe { heap::init_heap(); }

    // Exercise the heap so a regression fails loudly at boot: a growing `Vec`
    // (needs alloc+realloc) and a `Box` (needs alloc on the heap, not the stack).
    let mut nums = Vec::new();
    for i in 0..64 {
        nums.push(i * 3);
    }
    let sum: u32 = nums.iter().sum();
    let boxed = Box::new(0xA5u8);

    serial::write_str("LIONOS_HEAP_OK cap=");
    serial::write_dec(heap::KERNEL_ALLOC.capacity() as u64);
    serial::write_str(" used=");
    serial::write_dec(heap::KERNEL_ALLOC.used() as u64);
    serial::write_str(" sum=");
    serial::write_dec(sum as u64);
    serial::write_str(" box=");
    serial::write_hex(u64::from(*boxed));
    serial::write_str("\r\n");

    // --- Month 5: safe Canvas + double-buffer demo (after heap init so the
    // BackBuffer can allocate) ---
    if let Some(fb) = boot_info.framebuffer.as_mut() {
        let info = fb.info();
        let fw = info.width as usize;
        let fh = info.height as usize;
        let fpitch = (info.stride as usize).saturating_mul(info.bytes_per_pixel as usize);
        let fbpp = info.bytes_per_pixel as usize;
        let f_total = fpitch.saturating_mul(fh);
        // SAFETY: pitch/height came from the validation path earlier; the
        // mapped framebuffer is at least pitch*height bytes.
        let fb_slice =
            unsafe { core::slice::from_raw_parts_mut(fb.buffer_mut().as_mut_ptr(), f_total) };
        if let Some(mut front) = lionos_kernel::gfx::Canvas::new(fb_slice, fw, fh, fpitch, fbpp) {
            front.fill_rect(40, 40, 32, 32, 0x0000ff);
            serial::write_raw(b"LIONOS_GFX_CANVAS ok\r\n");
            // Double-buffer present + compositor/wallpaper/input-routing demo.
            if let Some(mut back) = lionos_kernel::gfx::BackBuffer::new(96, 64, 3) {
                // (a) animated diagonal-drift wallpaper on the back buffer, tick depends on
                //    the CPU (deterministic for a fixed VM), exercising the new
                //    drifting phase on top of the plain vertical gradient.
                use lionos_kernel::gfx::{Window, dock_pop, focus, paint_scene, wallpaper_drift};
                wallpaper_drift(&mut back.canvas, interrupts::ticks() as u32);
                serial::write_raw(b"LIONOS_GFX_WALL ok\r\n");
                // (b) a two-window compositor scene (painter's algorithm).
                let wins = [
                    Window { x: 4, y: 4, w: 40, h: 56, color: 0x00ff80 }, // bottom
                    Window { x: 20, y: 16, w: 26, h: 26, color: 0x0044ff }, // top
                ];
                paint_scene(&mut back.canvas, &wins);
                serial::write_raw(b"LIONOS_GFX_COMPOSITE nwins=");
                serial::write_dec(wins.len() as u64);
                serial::write_str("\r\n");
                // (c) input routing: focus the top-most window under the cursor.
                let focused = focus(&wins, 24, 24);
                serial::write_raw(b"LIONOS_GFX_FOCUS win=");
                serial::write_dec(focused.unwrap_or(0) as u64);
                serial::write_str("\r\n");
                // (d) present the composite to the front.
                let copied = front.blit_from(&back.canvas, 48, 48, 0, 0);
                serial::write_raw(b"LIONOS_GFX_DBLBUF present=");
                serial::write_dec(copied as u64);
                serial::write_str("\r\n");
                // (e) animation marker: the dock pop-ease and the wallpaper drift
                //     both run off the same PIT tick (deterministic per VM).
                serial::write_raw(b"LIONOS_GFX_ANIM tick=");
                serial::write_dec(interrupts::ticks() as u64);
                serial::write_raw(b" drift=");
                serial::write_dec(dock_pop(interrupts::ticks() as f32 * 0.05, 0, 2) as u64);
                serial::write_raw(b" pop=");
                serial::write_dec((interrupts::ticks() % 3) as u64);
                serial::write_str("\r\n");
            } else {
                serial::write_raw(b"LIONOS_GFX_DBLBUF_ERR\r\n");
            }
        } else {
            serial::write_raw(b"LIONOS_GFX_CANVAS_ERR\r\n");
        }
    }

    // --- Runtime component manifest (the `lionos setup` picker) ---
    // The enabled-component set chosen at install time, merged with the
    // compulsory core and embedded at build. Print it so CI can grep exactly
    // which components a given image was built with.
    serial::write_str("LIONOS_MANIFEST components=");
    serial::write_str(lionos_kernel::component_manifest::CSV);
    serial::write_str("\r\n");

    // --- Month 2: page-table ownership marker ---
    // The bootloader 0.11 does NOT identity-map its own page tables (reading
    // CR3's physical address faults), so the kernel cannot read/write them to
    // extend the map in place. True paging = building + switching to the
    // kernel's OWN page tables (a dedicated follow-up; `paging.rs` has the pure
    // index/entry helpers + tests). Here we only report our CR3 (a safe,
    // register-only read).
    serial::write_str("LIONOS_PML4 cr3=");
    serial::write_hex(paging::current_cr3());
    serial::write_str("\r\n");

    // Drain any deferred work the ISRs queued, then park with interrupts on so
    // the timer keeps ticking (future months run a scheduler here).
    interrupts::run_deferred();
    serial::write_str("LIONOS_IRQ_OK\r\n");

    // --- Month 3: device drivers ---
    // Beyond the plan's required serial/fb/text drivers (now formalized), this
    // inits the extra real drivers (RTC clock, PCI bus 0, VGA text, PC speaker,
    // keyboard decode, PS/2 mouse) + the simulated biometric gate. Runs after
    // interrupts are up (mouse ISR + PIC unmask are in interrupts::init).
    lionos_kernel::drivers::init_all();

    // --- Month 3: scheduler ---
    // Three tasks share ONE busy-counting closure (`task_closure`, module
    // scope); each runs it on its own stack, and the PIT preempts mid-count so
    // the shared ROTATIONS counter grows across all three — the interleave.
    sched::spawn(task_closure);
    sched::spawn(task_closure);
    sched::spawn(task_closure);
    // Close the ring (append the IDLE slot so the scheduler returns control to
    // the boot context), then convert PIT kicks into selection and switch.
    sched::finish();

    let mut spins = 0u64;
    while sched::switches() < 4 && spins < 500_000_000 {
        sched::pump_ticks();
        sched::run_pending_switch();
        ffi::pause();
        spins += 1;
    }
    serial::write_str("LIONOS_SCHED tasks=");
    serial::write_dec(sched::task_count() as u64);
    serial::write_str(" switches=");
    serial::write_dec(sched::switches());
    // SAFETY: single CPU boot; ROTATIONS is only written from tasks, all single-
    // threaded here.
    serial::write_str(" rot=");
    serial::write_dec(unsafe { ROTATIONS });
    serial::write_str("\r\n");

    // --- Month 6: simulated AI assistant stub (no ML; canned, honest) ---
    serial::write_raw(b"LIONOS_AI_STUB reply=\"");
    for b in lionos_kernel::ai::answer("hello").bytes() {
        serial::write_byte(b);
    }
    serial::write_str("\"\r\n");

    // --- Month 6: Path-A apps (theme, editor, explorer, dock) ---
    let t = lionos_kernel::theme::Theme::dark();
    serial::write_raw(b"LIONOS_THEME t=");
    serial::write_str(t.name);
    serial::write_str("\r\n");

    let mut ed = lionos_kernel::editor::TextBuffer::new();
    ed.put(b"LionOS");
    ed.backspace(ed.len()); // drop the trailing 's'
    serial::write_raw(b"LIONOS_EDITOR len=");
    serial::write_dec(ed.len() as u64);
    serial::write_str("\r\n");

    // Explorer reports the number of files on the last FAT mount; when no disk
    // is mounted this is 0 (the FS driver already logs LIONOS_FS_NONE_MOUNTED).
    serial::write_raw(b"LIONOS_EXPLORER files=");
    serial::write_dec(lionos_kernel::drivers::last_fs_files() as u64);
    serial::write_str("\r\n");

    serial::write_raw(b"LIONOS_DOCK napps=");
    serial::write_dec(lionos_kernel::dock::app_count() as u64);
    serial::write_str("\r\n");

    // --- Month 4: ring-3 + syscall bring-up (the last boot action) ---
    // Descend to ring 3 and round-trip a few `syscall`s. `bring_up` returns
    // false only when it could NOT descend (CPU lacks `syscall`, or no free low
    // region); on success it iretq's to ring 3 and never returns. If it could
    // not descend we carry on with the ring-0 idle loop.
    if !(unsafe { lionos_kernel::user::bring_up() }) {
        sched::idle_loop();
    }

    // After `bring_up` descended we can never reach this point; if it returned
    // false the idle loop above is already spinning.
    unreachable!()
}

// Bootloader config: enable the physical-memory mapping so `BootInfo`
// exposes `physical_memory_offset` — the virt window over the whole physical
// address space. This is the M2W3c unblock: it lets the kernel read/write any
// physical frame (incl. the bootloader's own page-table frames, which are
// otherwise NOT virt-accessible), so the kernel can build and switch to its
// own page tables. `entry_point!(config = …)` is how a custom 0.11 config is
// passed (the default `entry_point!(f)` is `config = new_default()`, which
// leaves `physical_memory` = None — exactly why takeover was blocked).
static BOOT_CONFIG: BootloaderConfig = {
    // Mappings is #[non_exhaustive], so mutate the field on the default rather
    // than building a literal.
    let mut c = BootloaderConfig::new_default();
    c.mappings.physical_memory = Some(Mapping::Dynamic);
    c
};

entry_point!(kernel_main, config = &BOOT_CONFIG);

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    serial::init();
    serial::write_raw(b"PANIC\r\n");
    ffi::hlt();
}
